name: Release Please
on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      # Debug step to check token permissions (optional)
      - name: Check token permissions
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/collaborators/${{ github.actor }}/permission | jq
          
      # Main Release Please step
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug manifest
        run: |
          echo "Current manifest:"
          cat .release-please-manifest.json
          echo -e "\nDirectory structure:"
          tree -L 3 src/code

      - name: Run Release Please
        uses: googleapis/release-please-action@v4
        with:
          release-type: "python"
          manifest-file: ".release-please-manifest.json"
          config-file: ".release-please-config.json"
          token: ${{ secrets.GITHUB_TOKEN }}
          fork: false
          skip-labeling: true
          changelog-host: "https://github.com"