name: Release Please
on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate JSON
        run: |
          # Check if manifest is valid JSON
          if ! jq empty .release-please-manifest.json 2>/dev/null; then
            echo '{".":"1.0.0","src/code/package1":"0.1.0","src/code/package2":"0.1.0"}' > .release-please-manifest.json
          fi

      - name: Run Release Please
        uses: googleapis/release-please-action@v4
        with:
          release-type: "python"
          manifest-file: ".release-please-manifest.json"
          config-file: "release-please-config.json"
          token: ${{ secrets.GITHUB_TOKEN }}
          