name: Release Please
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history needed for version analysis
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Release Please
        id: release-please
        uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: "release-please-config.json"
          command: manifest  # Required for monorepo support
          release-type: node  # Works best with manifest command
          package-name: "python-monorepo"
          monorepo-tags: true
          bump-minor-pre-major: true
          include-v-in-tag: true
          pull-request-title-pattern: "chore: release ${version}"
          changelog-types: |
            [{"type":"feat","section":"Features","hidden":false},
             {"type":"fix","section":"Bug Fixes","hidden":false},
             {"type":"chore","section":"Maintenance","hidden":false}]

      - name: Debug Output
        if: always()
        run: |
          echo "Release Please output:"
          echo "${{ steps.release-please.outputs }}"