name: Release Please
on:
  push:
    branches: [main]

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: "python"
          manifest-file: ".release-please-manifest.json"
          config-file: ".release-please-config.json"
          token: ${{ secrets.GITHUB_TOKEN }}