name: Release Please
on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - name: Setup root version file
      #   run: |
      #     # Create root version file if missing
      #     if [ ! -f root-version.txt ]; then
      #       echo "1.0.0" > root-version.txt
      #       git add root-version.txt
      #       git commit -m "chore: initialize root version" || true
      #     fi

      - name: Run Release Please
        uses: googleapis/release-please-action@v4
        with:
          release-type: "node"
          config-file: "release-please-config.json"
          token: ${{ secrets.GITHUB_TOKEN }}
          skip-labeling: true